### ISSUE TITLE
performance improvement parent issue

### ISSUE THREAD

**Issue by yishanhe** [wuhanunited/wuhanunited-dev#3]
https://wuhanunited.org/%e5%b8%ae%e5%8a%a9%e9%80%94%e5%be%84/

**Comment by yishanhe** [comment]
https://wordpress.org/plugins/wp-smushit/

**Comment by yishanhe** [comment]
https://gtmetrix.com/reports/beta.wuhanunited.org/Ano1KDOu

- [ ] server scaled images
- [ ] leverage browser caching
- [ ] optimize images
- [ ] add expires headers
- [ ] use a CDN
- [ ] make fewer https requests

**Comment by yishanhe** [comment]
similar result from here https://tools.pingdom.com/#5c061108e8c00000

**Comment by yishanhe** [comment]
the latest run of https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwuhanunited.org%2F gives 87 on mobile and 92 on desktop, which is pretty good now.

**Comment by yishanhe** [comment]
https://gtmetrix.com/reports/wuhanunited.org/jeuDExHY gives pretty good score now.

**Comment by yishanhe** [comment]
almost all the performance improvements have been addressed, closing this issue
